### ISSUE TITLE
Exporting bones bug

### ISSUE THREAD

**Issue by space928** [space928/Blender-O3D-IO-Public#27]
### Describe the bug
Exporting o3d files with bones raises an exception

### Additional context
```
Python: Traceback (most recent call last):
File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Blender-O3D-IO\__init__.py", line 160, in execute 
io_o3d_export.do_export(self.filepath, context, global_matrix, self.use_selection, self.o3d_version)
File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Blender-O3D-IO\o3d_io\io_o3d_export.py", line 168, in do_export 
export_mesh(path, context, me, ob_eval.material_slots, o3d_version)
File "C:\Users\****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Blender-O3D-IO\o3d_io\io_o3d_export.py", line 87, in export_mesh
for m_bone in mesh.bones:

AttributeError: 'Mesh' object has no attribute 'bones'

location: <unknown location>:-1
```

**Comment by space928** [comment]
Fixed in 47df7c0eebeda11c4136d01e94ecd9229c0105a5
