### ISSUE TITLE
Null reference exception on export when the material has no texture

### ISSUE THREAD

**Issue by space928** [space928/Blender-O3D-IO-Public#41]
### Describe the bug
```
Traceback (most recent call last):
  File "C:\Users\Super PC\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-O3D-IO-Public\__init__.py", line 168, in execute
    io_o3d_export.do_export(self.filepath, context, global_matrix, self.use_selection, self.o3d_version)
  File "C:\Users\Super PC\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-O3D-IO-Public\o3d_io\io_o3d_export.py", line 235, in do_export
    export_mesh(path, context, ob_eval, me, ob_eval.material_slots, o3d_version)
  File "C:\Users\Super PC\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-O3D-IO-Public\o3d_io\io_o3d_export.py", line 133, in export_mesh
    if mat.base_color_texture.image is not None:
AttributeError: 'NoneType' object has no attribute 'image'
```

### To Reproduce
Steps to reproduce the behaviour:
[Be sure to attach any relevant files (o3d, cfg, dds, etc...) to the issue or provide a link to them here]

### Additional context
Blender 3.4

**Comment by space928** [comment]
Fixed in next release.
